---
# yamllint disable rule:key-ordering
stages:
  - test
  - build
  - tag
  - release

variables:
  GOPROXY: https://proxy.golang.org,direct
  GOPRIVATE: github.com/lana,gitlab.lana.tech

.git: &git_template
  before_script:
    - printf "machine gitlab.lana.tech login github-bot password ${GITLAB_TOKEN}\nmachine github.com login lana-dev password ${GITHUB_ACCESS_TOKEN}" > ~/.netrc
    - git config --global url."https://lana-dev:${GITHUB_ACCESS_TOKEN}@github.com".insteadOf "https://github.com"

.go: &go
  image: gitlab.lana.tech:5005/infrastructure/docker/docker-ci-golang-debian/docker-ci-golang-debian:latest

.front: &front
  image: node:alpine

.docker: &docker
  image: gitlab.lana.tech:5005/infrastructure/docker/docker-ci-builder/docker-ci-builder:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay2"
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

go-linter:
  <<: *git_template
  <<: *go
  stage: test
  script:
    - go mod download
    - |
        go mod tidy
        if [ -n "$(git diff-index --name-only HEAD --)" ]; then 
            echo -e "***\n***\n*** Please run 'go mod tidy':\n***\n***"
            git -c color.ui=always diff | head -n25
            exit 1
        fi
    - golangci-lint run ./...

go-test:
  <<: *git_template
  <<: *go
  stage: test
  script:
    - go build ./...
    - go test -race ./...

tag-check:
  stage: test
  image: gitlab.lana.tech:5005/infrastructure/docker/docker-base-debian/docker-base-debian:latest
  script:
    - bash ./scripts/tag-check.sh
  except:
    - master
    - tags

tag:
  stage: tag
  image: gitlab.lana.tech:5005/infrastructure/docker/docker-base-debian/docker-base-debian:latest
  script:
    - bash ./scripts/tag.sh
  only:
    - master
